# Generated by Django 3.1.3 on 2020-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
