# Generated by Django 3.1.3 on 2020-12-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_order_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ManyToManyField(null=True, to='accounts.Seller'),
        ),
    ]
