# Generated by Django 3.1.3 on 2020-12-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201217_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ManyToManyField(to='accounts.Seller'),
        ),
    ]
